apiVersion: apps/v1
kind: Deployment
metadata:
  name: "descheduler"
  namespace: "openshift-kube-descheduler-operator"
  labels:
    app: "descheduler"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "descheduler"
  template:
    metadata:
      labels:
        app: "descheduler"
    spec:
      volumes:
        - name: "policy-volume"
          configMap:
            name: "descheduler"
      priorityClassName: "system-cluster-critical"
      restartPolicy: "Always"
      containers:
        - name: "openshift-descheduler"
          image: "quay.io/openshift/origin-descheduler:4.7"
          resources:
            limits:
              cpu: "100m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "500Mi"
          command: ["/bin/descheduler"]
          args:
            - --policy-config-file=/policy-dir/policy.yaml
            - --v=2
          volumeMounts:
            - mountPath: "/policy-dir"
              name: "policy-volume"
      serviceAccountName: "openshift-descheduler"
