kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: descheduler-operator
rules:
- apiGroups:
  - descheduler.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - configmaps
  - secrets
  - names
  - nodes
  - pods/eviction
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: descheduler-role-binding 
subjects:
- kind: ServiceAccount
  name: openshift-descheduler
  namespace: openshift-descheduler-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: descheduler-operator
