kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: descheduler-operator
rules:
- apiGroups:
  - descheduler.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - configmaps
  - secrets
  - names
  - nodes
  - pods/eviction
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs:
  - "*"
